apiVersion: apps/v1
kind: Deployment
metadata:
  name: store owner
  labels:
    app: store owner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store owner
  template:
    metadata:
      labels:
        app: store owner
    spec:
      containers:
        - name: store owner
          image: username/store owner:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
