server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: rider
          uri: http://localhost:8081
          predicates:
            - Path=/deliveries/**, 
        - id: store owner
          uri: http://localhost:8082
          predicates:
            - Path=/cookings/**, 
        - id: hunger
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rider
          uri: http://rider:8080
          predicates:
            - Path=/deliveries/**, 
        - id: store owner
          uri: http://storeOwner:8080
          predicates:
            - Path=/cookings/**, 
        - id: hunger
          uri: http://hunger:8080
          predicates:
            - Path=/orders/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
